# The Docker image that will be used to build your app
image: alpine:latest
pages:
  stage: deploy
  script:
    - mkdir -p /tmp/build_assets
    - cp -r . /tmp/build_assets/
    - mkdir -p public;
    - cp -r /tmp/build_assets/* public/;
  artifacts:
    paths:
      - public
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    variables:
      PAGES_PREFIX: ""
      ENV_NAME: "production"
      ENV_URL: $CI_PAGES_URL
  - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
    variables:
      PAGES_PREFIX: "$CI_COMMIT_REF_SLUG"
      ENV_NAME: "review/$CI_COMMIT_REF_NAME"
      ENV_URL: $CI_PAGES_URL
  pages:
    path_prefix: "$PAGES_PREFIX"
  environment:
    name: $ENV_NAME
    url: $ENV_URL
